### PR TITLE
allow nginx configuration extension through /etc/nginx/conf.d/*.conf

### PR DESCRIPTION
**Pull request by jvies**

### CODE REVIEW

**Comment by jvies** [comment]
OK... I think I pushed too quickly :)

I'll do some other tests

**Comment by jvies** [comment]
My local test runs fine. As far as I understand, the test that fails checks a button with "Sign in" is present. On my local deployment, this button does not exist, as the page displayed is the installer wizard.
Any idea why my local deployment is different on from on the test deployment ?

**Comment by mriedmann** [comment]
In theory the test step should start the auto-installer. Maybe you haven't called that locally? Also it could be that it is simply broken.

**Comment by jvies** [comment]
I built the docker image locally (using `docker build . --tag humhub:master --build-arg HUMHUB_VERSION=1.11.4`
It starts, but I can't find any button with "Sign in".
The only available buttons are:
```
            <!-- Footer -->
                            <div class="modal-footer">
                    <button data-modal-cancel data-modal-close class="btn btn-default"></button><button data-modal-confirm data-modal-close class="btn btn-primary"></button>                </div>
                        </div>
</div>   
```
This happens on master, as on my own branch. Any idea why ?

**Comment by mriedmann** [comment]
ok, this makes more sense now ... we most likely have to clear out the /etc/nginx/conf.d directory in the nginx base-image. Currently, we are ignoring those files but with your change this will mess up our config.

@jvies  Can you try to add a "RUN rm -rf /etc/nginx/conf.d" before the copy step in on the nginx image in the Dockerfile? This should fix the pipeline. Will merge it if it runs green.

**Comment by mriedmann** [comment]
I might made an error sorry ... deleting the dir might not be what we wanted ... rather deleting the content of it `RUN rm /etc/nginx/conf.d/*`

sorry

**Comment by jvies** [comment]
seems better thx !
I rebase and push again.

**Pull request merged**
