### PR TITLE
Feat/reverseproxy whitelist

### PR DESCRIPTION
**Pull request by r4nc0r**
Added Enviroment variable HUMHUB_REVERSEPROXY_WHITELIST for #177 

This Env variable is split by the charater `;`
Each IP is added in an extra file `/etc/nginx/allowedips.conf`  in the `docker-entrypoint.sh`
This file is included in the nginx.conf

### CODE REVIEW

**Comment by r4nc0r** [comment]
it works locally on my machine, could you help me find the error?

**Comment by mriedmann** [comment]
I will have a look. Thx for the PR.

**Comment by mriedmann** [comment]
just a short explanation on the situation: We are currently building and testing to different "tracks" of this image. One "AllInOne" (aio) and one "Prod" (that has nginx and php separated). To introduce new features to the nginx in both tracks you have to use the docker-entrypoint.d files because they will be executed by both entrypoint-scripts (aio and nginx). That's also most likely why you haven't experienced any problems locally. I guess you have only tested the allinone image and not both (which is hard to test, I know ;-) )

I will gladly accept the PR now, thx for your contribution.

One small thing: During my tests, dropping the final semicolon worked just fine. Is there any special case where this leads to problems?

**Comment by r4nc0r** [comment]
OK, next time i will test it with the seperated image too :)

as long as there is any semicolon, it will work because the trying is splitted by it. When there is none it fails maybe adding a check for the semi is a good idea :)

**Comment by r4nc0r** [comment]
Updated Readme, ready to merge :)

**Comment by mriedmann** [comment]
Thank you very much :)

**Pull request merged**
