### PR TITLE
✨ Add env var to set admin credentials

### PR DESCRIPTION
**Pull request by madmath03**
:sparkles: Add env var to set admin credentials

Signed-off-by: mathieu.brunot <mathieu.brunot@monogramm.io>

### CODE REVIEW

**Comment by madmath03** [comment]
The more I look at the Install command, the more I think:
1. this could be split in 2: an Installer and a User command
2. this would be just great to integrate this directly in HumHub (cf #110)

what do you think ?

**Comment by mriedmann** [comment]
@madmath03 Thank you for the Humhub PR. We could merge this one and simply remove the file after the PR is accepted by humhub. Personally I don't mind this "patch". It has limited complexity and serves a very special purpose. My concern is that we slow down our own development speed by binding it to the process of the upstream project (due to the "shared" installer file). We can still provide PRs but I am not sure if it is necessary to rely on the file inside the humhub project.

Normally I would avoid such things, but in this special situation it looks more like an adapter then a hack. 

What do you think?

**Comment by madmath03** [comment]
> @madmath03 Thank you for the Humhub PR. We could merge this one and simply remove the file after the PR is accepted by humhub. Personally I don't mind this "patch". It has limited complexity and serves a very special purpose. My concern is that we slow down our own development speed by binding it to the process of the upstream project (due to the "shared" installer file). We can still provide PRs but I am not sure if it is necessary to rely on the file inside the humhub project.
> 
> Normally I would avoid such things, but in this special situation it looks more like an adapter then a hack.
> 
> What do you think?

I was also thinking about merging this in case there is a big delay until the HumHub PR is merged.

I think it's ok temporarily, but once it's merged it should be ok to remove the file and rely on HumHub if this image becomes the "_official_" HumHub image (following discussion in #116).

> EDIT:
> I also had a look at this PR: https://github.com/humhub/humhub/pull/4341/files
> 
> Maybe we also could try to write a minimal "advanced installer" module inside this repo to have an even better interface avoiding this "hack-fix" all together. Just an idea.

I looked quickly at this PR but I'm not sure about how to do this so far. Will check more details later.

**Comment by mriedmann** [comment]
as commented here: https://github.com/humhub/humhub/pull/4345 I will merge this to go forward with this. We will refine this later.

**Pull request merged**
