### PR TITLE
update to 1.14.5 as stable

### PR DESCRIPTION
**Pull request by jvies**

### CODE REVIEW

**Comment by ArchBlood** [comment]
Remember that v1.15 is PHP 8.0.x+

**Comment by jvies** [comment]
I didn't checked that point...
Their use to be a php8 branch, but it was never merged. Was it broken ?

**Comment by jvies** [comment]
Pipeline checks are all ok. Is it php8 only ?
According to the migration guide (https://docs.humhub.org/docs/admin/updating-migration2/#115), php 7.4 is still the minimum version.

**Comment by jvies** [comment]
You're right the Dockerfile uses php8.

According to the Humhub info panel, we run on "PHP - Version - 7.4.33".

Weird. I'll check why.

**Comment by jvies** [comment]
ok. found it. my clone is not correctly rebased on your master :)

**Review by mriedmann — APPROVED** [review]

**Pull request merged**
