### PR TITLE
Adjustmeants for run with success

### PR DESCRIPTION
**Pull request by cesardraw2**
Details in commit's comments.

### CODE REVIEW

**Comment by cesardraw2** [comment]
Last commit with success!
https://hub.docker.com/r/cesardraw/humhub2-docker/builds

**Comment by mriedmann** [comment]
Hi! Thank you for your paticipation.

Your changes look good, I will test them as soon as possible.
Only one thing that is a bit odd: Why are you using your HumHub repo instead of the official one? Any good reasons or just a leftover?

**Comment by mriedmann** [comment]
Hey ... Thank you for your ideas and help. I've integrated most of them by hand (because it was easier/faster for me). If you get further commits I would suggest that you "rebase" your Repo to the new master-branch and open a new pull request.

**Comment by cesardraw2** [comment]
Hi, @mriedmann!

I use my repository humhub for testing with Docker and test new possibilities , helping to develop the tool with new ideas.

Congratulations on your excellent work !

I did the commit in " zombie mode " : D
during the morning and forgot to create a new branch , sorry !

I will make the re- base!

**Pull request closed without merging**
