### PR TITLE
Moved HumHub_LDAP_Cert settings

### PR DESCRIPTION
**Pull request by r4nc0r**
Moved the Configuration because these Files are not persisted on container restart and need to be configured on every container start.

### CODE REVIEW

**Comment by r4nc0r** [comment]
@mriedmann could you merge this?

**Comment by mriedmann** [comment]
sorry completely forgot about that. The change is not released to docker-hub automatically anymore, I assume you also need a release to the latest tag, right?

**Comment by r4nc0r** [comment]
yes that would be nice :)

**Comment by mriedmann** [comment]
currently I have no time to fix the latest release step to docker-hub but you can use the github registry: https://github.com/users/mriedmann/packages/container/package/humhub ... just pull the master-1.7.2-allinone image (if you are using the normal 1.7 or 1.7.2 tag)

**Pull request merged**
