### PR TITLE
Better Composer installation

### PR DESCRIPTION
**Pull request by bkmeneguello**
Better Composer installations as stated in https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md

### CODE REVIEW

**Comment by mriedmann** [comment]
Hi!

Thanks for putting this much afford into "my" old humhub image, but your change here looks a bit controversial to me.

I hard coded the SHA-hash to prevent a building machine form using a fake composer image. In my opinion it is good practice to check every potentially compromised dependency at build-time.

If this is somehow wrong or not state-of-the-art any more I would love to have a short discussion about this matter. I'am not really satisfied with my solution, so if you got some facts that this method is safe, I will approve your change immediately.

Cheers,
Michael

**Comment by bkmeneguello** [comment]
Hi
Well, I do agree with you that tampering this download is an issue. But, as I said in PR, I'm following the rules pointed by official provider.
My problem occurred when I tried to build the image and the image hash diverged from downloaded. So I looked for an official solution, found in documentation.

**Comment by mriedmann** [comment]
The last 1h I looked into this topic a bit more and found the new ARG keyword (https://docs.docker.com/engine/reference/builder/#arg). In future this could be used to inject the hash in a save way. Unfortunately it is not supported by docker-hub at the moment, so for now I agree with you that "stabilizing" the build process is more important then securing it. In the future I really hope that there will be a better/safer alternative to this solution.

I really thank you for holding this image alive, I stopped using it for some time and got little to no time maintaining it.

**Comment by bkmeneguello** [comment]
You left humhub for another platform? Let me know.
I'm looking for a way to upgrade the minor version to 1.2.2, but it breaks.

**Pull request merged**
